### ISSUE TITLE
Automatic fetch the serial from the internet

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#18] opened 2018-07-29 12:50 UTC
If the current local serial is invalid try to update the serial from the Internet

see q2g/se-l#5

**Comment by ChristofHoldschick** [comment] 2018-11-26 09:53
Just before the LEF-Window opens, try to fetch the license from qlik2go.net and check if it is valid.

**Comment by ChristofHoldschick** [comment] 2019-02-22 06:17
duplicate of https://github.com/senseexcel/senseexcel/issues/76

**Closed by ChristofHoldschick** 2019-02-22 06:17 UTC
